version: '2'

services:
  db:
    image: postgres:13
    restart: always
    shm_size: '3gb'
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: 
      - ./db.env
    expose: 
      - "5432"
 
  api:
    build:
      context: ./src/go-api/
    depends_on: 
      - db
    expose: 
      - "3000"
    env_file:
      - ./api.env

  nginx:
    build:
      context: ./
      dockerfile: ./fe/Dockerfile
    depends_on: 
      - api
    volumes: 
      - ./nginx/:/etc/nginx/
      - ./certs/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  
volumes: 
  db-data:

