services:
  migrations:
    image: ghcr.io/marekvigas/postar-jano/api:master
    command: "/app/bin/registrations_api migrate"
    env_file: api.env
    networks:
      - backend
    depends_on:
      - db
  
  db:
    image: postgres:16
    networks:
      - backend
    env_file: db.env
    volumes:
      - /root/salezko/db:/var/lib/postgresql/data
  
  api:
    image: ghcr.io/marekvigas/postar-jano/api:master
    networks:
      - backend
      - cloudflared
    volumes:
      - /root/salezko/promo.html:/tmp/promo.html
      - /root/salezko/confirmation.html:/tmp/confirmation.html
      - /root/salezko/payment.html:/tmp/payment.html
    env_file: api.env
    depends_on:
      - db
      - migrations
    restart: unless-stopped

  form:
    image: ghcr.io/marekvigas/postar-jano/form:master
    networks:
      - cloudflared

  admin:
    image: ghcr.io/marekvigas/postar-jano/admin:master
    networks:
      - cloudflared

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - cloudflared
      - backend
    volumes:
      - /root/salezko/pgadmin:/var/lib/pgadmin

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflare_token
    networks:
      - cloudflared
    restart: unless-stopped
    secrets:
      - cloudflare_token

secrets:
  cloudflare_token:
    file: ./cloudflared_token.env

networks:
  backend:
  cloudflared: