version: "3.8"

services:
  db:
    image: marekvigas/sbb-leto-db:master
    networks:
      - backend
    env_file: db.env
    volumes:
      - /root/salezko/db:/var/lib/postgresql/data
  api:
    image: marekvigas/sbb-leto-api:master
    ports:
      - "5000:5000"
    networks:
      - backend
    volumes:
      - /root/salezko/email.html:/tmp/email.html
    env_file: api.env
    deploy:
      # replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
  form:
    image: marekvigas/sbb-leto-form:sbb
    ports:
      - "4000:80"
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - /root/salezko/pgadmin:/var/lib/pgadmin
    env_file: pgadmin.env
    ports:
     - "5050:80"
    networks:
      - backend

  pgbackups:
    image: prodrigestivill/postgres-backup-local:13-alpine
    user: postgres:postgres
    volumes:
      - /root/salezko/backups:/backups
    env_file: pgbackups.env
    networks:
      - backend

networks:
  backend: