services:
  db:
    image: postgres:16
    env_file:
      - db.env

  migrations:
    build:
      context: ../src/go-api
      target: devImage
    image: api-image
    restart: on-failure
    command: "/src/registrations_api migrate"
    env_file:
      - api.env
    depends_on:
      - db

  api:
    image: api-image
    env_file:
      - api.env
    volumes:
      - ../src/go-api:/src
      - ../templates:/templates
    command: "/src/registrations_api"
    ports:
      - "127.0.0.1:48080:5000"
    depends_on:
      - migrations

  fe:
    build:
      context: ../admin
      args:
         REACT_APP_API_HOST: http://localhost:48080
    ports:
      - "127.0.0.1:48081:80"
    depends_on:
      - api
