name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: leto
        ports:
          - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0' # The Go version to download (if necessary) and use.
        
    # Run build of the application
    - name: Build
      run: |
        cd src/go-api
        make build 

    - name: Unit tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: leto
        EMAIL_TEMPLATE_PATH: '${{ github.workspace }}/email_tabor.html'
      run: |
        cd src/go-api
        echo $EMAIL_TEMPLATE_PATH
        make test
    
  # # The "deploy" workflow
  # deploy:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   needs: [build] # Only run this workflow when "build" workflow succeeds
  #   if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
  #   steps:
  #   - uses: actions/checkout@v2

  #   # Deploy to Docker registry
  #   - name: Deploy to Docker registry
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       repository: wilsontanwm/gosimple
  #       tag_with_ref: true